<#
.SYNOPSIS
    Exports all Group Policy Objects to a structured HTML report.

.DESCRIPTION
    Generates a full GPO inventory: name, GUID, linked OUs, status,
    creation/modification dates, and WMI filters. Exports each GPO
    as individual HTML + a master index report.

.PARAMETER OutputPath
    Directory where reports will be saved. Default: C:\Reports\GPO

.PARAMETER DomainController
    Target DC. Defaults to current.

.EXAMPLE
    .\Export-GPOReport.ps1
    .\Export-GPOReport.ps1 -OutputPath "D:\Audits\GPO-$(Get-Date -Format 'yyyyMMdd')"

.NOTES
    Author   : Aymerick Victoire
    Requires : GroupPolicy PowerShell module (RSAT: Group Policy Management)
    Purpose  : GPO documentation, change tracking, compliance
#>

param (
    [string]$OutputPath = "C:\Reports\GPO",
    [string]$DomainController = ""
)

#Requires -Modules GroupPolicy

$ErrorActionPreference = "Stop"

# Create output dir
if (-not (Test-Path $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory | Out-Null
}

Write-Host "[*] Exporting GPOs to: $OutputPath" -ForegroundColor Cyan

$Domain = Get-ADDomain
$GPOs = Get-GPO -All -Domain $Domain.DNSRoot

Write-Host "[*] Found $($GPOs.Count) GPOs" -ForegroundColor Cyan

$GPOIndex = @()

foreach ($GPO in $GPOs) {
    Write-Host "  [>] $($GPO.DisplayName)" -ForegroundColor Gray

    # Export individual GPO report
    $SafeName = $GPO.DisplayName -replace '[\\/:*?"<>|]', '_'
    $ReportPath = Join-Path $OutputPath "$SafeName.html"
    Get-GPOReport -Guid $GPO.Id -ReportType HTML -Path $ReportPath

    # Get linked OUs
    $Links = (Get-GPOReport -Guid $GPO.Id -ReportType XML) -as [xml]
    $LinkedOUs = $Links.GPO.LinksTo.SOMPath -join "; "

    $GPOIndex += [PSCustomObject]@{
        Name              = $GPO.DisplayName
        Status            = $GPO.GpoStatus
        ComputerEnabled   = $GPO.Computer.Enabled
        UserEnabled       = $GPO.User.Enabled
        Created           = $GPO.CreationTime
        Modified          = $GPO.ModificationTime
        LinkedOUs         = $LinkedOUs
        WMIFilter         = $GPO.WmiFilter.Name
        GUID              = $GPO.Id
        IndividualReport  = "$SafeName.html"
    }
}

# Master index HTML
$IndexHtml = $GPOIndex | ConvertTo-Html `
    -Title "GPO Inventory — $($Domain.DNSRoot)" `
    -PreContent "<h1>GPO Inventory — $($Domain.DNSRoot)</h1><p>Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm') | Total: $($GPOs.Count) GPOs</p>" `
    -PostContent "<p><small>Generated by Export-GPOReport.ps1</small></p>"

$IndexPath = Join-Path $OutputPath "_index.html"
$IndexHtml | Out-File -FilePath $IndexPath -Encoding UTF8

Write-Host "`n[+] Index report: $IndexPath" -ForegroundColor Green
Write-Host "[+] Individual reports: $OutputPath\*.html" -ForegroundColor Green
Write-Host "[+] Export complete — $($GPOs.Count) GPOs documented." -ForegroundColor Green
